version: '3.9'
services:
  app:
    container_name: go-api
    tty: true
    stdin_open: true
    restart: on-failure
    ports:
      - 8080:8080
    build:
      context: ./..
      dockerfile: Dockerfile
    image: go-alpine
    env_file:
      - ./../.env
  db:
    container_name: postgres
    image: postgres:alpine3.16
    ports:
      - 5432:5432
    env_file:
      - ./db.env